In [1]:
# Part 4: Find the rectifying homography

In [2]:
import numpy as np
import cv2
import sys

In [60]:
horVP = np.load('horVP.npy')
vertVP = np.load('vertVP.npy')
transversalVP = np.load('transversalVP.npy')
K = np.load('newcameramtx.npy')
Kinv = np.linalg.inv(K)
srcImage = cv2.imread('images/buildingUndistorted.jpg')
# srcImage = cv2.imread('images/buildingUndistortedWithLines.jpg')
destPathW = 'images/buildingTransformedW.jpg'
destPathR = 'images/buildingTransformedR.jpg'

In [4]:
# horVP = -horVP
vertVP = -vertVP
print(horVP)
print(vertVP)
print(transversalVP)

[-0.5740622  -0.04770422 -0.81742088]
[-0.01921299 -0.99093285  0.13297723]
[ 0.81739148 -0.09215941 -0.56866318]


In [5]:
W = np.stack((horVP, vertVP, transversalVP))
WInv = np.linalg.inv(W)
R = W.transpose()
R

array([[-0.5740622 , -0.01921299,  0.81739148],
       [-0.04770422, -0.99093285, -0.09215941],
       [-0.81742088,  0.13297723, -0.56866318]])

In [55]:
Ht = np.array([[1, 0, -1020],
     [0, 1, 3960],
     [0, 0, 1]])

In [56]:
Hw = np.dot( Ht, np.dot( np.dot(K, W), Kinv ) )
Hr = np.dot( Ht, np.dot( np.dot(K, R), Kinv ) )

In [61]:
transformedImageW = cv2.warpPerspective(srcImage, M = Hw, dsize = (7745, 5510))
# cv2.imshow('img-W', transformedImageW)
# cv2.waitKey(5000)
# cv2.destroyAllWindows()
cv2.imwrite(destPathW, transformedImageW)

True

In [9]:
transformedImageR = cv2.warpPerspective(srcImage, M = Hr, dsize = (4000, 2500))
# cv2.imshow('img-R', transformedImageR)
# cv2.waitKey(5000)
# cv2.destroyAllWindows()
cv2.imwrite(destPathR, transformedImageR)

True

In [62]:
H = np.dot( np.dot(K, W), Kinv )
H / H[2,2]

array([[ 6.50108503e-02,  1.02515826e-01,  1.02672899e+03],
       [-3.49120784e-01,  1.00164168e+00, -1.18233470e+02],
       [-8.06154250e-04,  9.17405309e-05,  1.00000000e+00]])

In [11]:
# lets check the 4 corners
c1 = np.array([0, 0, 1])
c2 = np.array([1086, 0, 1])
c3 = np.array([1086, 804, 1])
c4 = np.array([0, 804, 1])

d1 = np.dot(H, c1)
d2 = np.dot(H, c2)
d3 = np.dot(H, c3)
d4 = np.dot(H, c4)

In [12]:
print(d1.astype('int'))
print(d2.astype('int'))
print(d3.astype('int'))
print(d4.astype('int'))

[-1060   122    -1]
[-1132   513     0]
[-1218  -317     0]
[-1145  -709    -1]
