In [1]:
# Part 3: Find bundles of parallel lines

In [2]:
import numpy as np
import cv2
from PIL import Image, ImageDraw

In [9]:
"""Run the draw tool to get points for parallel lines. 
This may not work on cloud. If it doesn't download the project and run it in local computer
ESC to quit the drawing tool and save the points.
Parameters: 
    1 path of the image relative to images folder
    2 name of the output file. default is buildingLines. Should be overrided if to be used for different sets of points.
output:
    an npy file with coordinates for lines."""
%run .\drawTool.py buildingUndistorted.jpg horizontalLines

Image H and W 804 1086
TOP_LEFT  (621, 311)
BOTTOM_RIGHT (719, 325)
TOP_LEFT  (626, 425)
BOTTOM_RIGHT (720, 430)
TOP_LEFT  (628, 467)
BOTTOM_RIGHT (721, 467)
TOP_LEFT  (800, 712)
BOTTOM_RIGHT (863, 695)
TOP_LEFT  (813, 481)
BOTTOM_RIGHT (898, 479)
TOP_LEFT  (954, 434)
BOTTOM_RIGHT (998, 436)
TOP_LEFT  (957, 311)
BOTTOM_RIGHT (994, 318)
TOP_LEFT  (677, 151)
BOTTOM_RIGHT (846, 201)
TOP_LEFT  (738, 60)
BOTTOM_RIGHT (904, 129)
saved line points in horizontalLines.npy


In [15]:
%run .\drawTool.py buildingUndistorted.jpg verticalLines

Image H and W 804 1086
TOP_LEFT  (734, 276)
BOTTOM_RIGHT (740, 471)
TOP_LEFT  (804, 296)
BOTTOM_RIGHT (810, 453)
TOP_LEFT  (888, 314)
BOTTOM_RIGHT (894, 458)
TOP_LEFT  (945, 324)
BOTTOM_RIGHT (951, 459)
TOP_LEFT  (1007, 326)
BOTTOM_RIGHT (1012, 460)
TOP_LEFT  (1044, 337)
BOTTOM_RIGHT (1051, 455)
saved line points in verticalLines.npy


In [16]:
horizontalLines = np.load('horizontalLines.npy')
verticalLines = np.load('verticalLines.npy')
print(horizontalLines)
print(verticalLines)

[[[621 311]
  [719 325]]

 [[626 425]
  [720 430]]

 [[628 467]
  [721 467]]

 [[800 712]
  [863 695]]

 [[813 481]
  [898 479]]

 [[954 434]
  [998 436]]

 [[957 311]
  [994 318]]

 [[677 151]
  [846 201]]

 [[738  60]
  [904 129]]]
[[[ 734  276]
  [ 740  471]]

 [[ 804  296]
  [ 810  453]]

 [[ 888  314]
  [ 894  458]]

 [[ 945  324]
  [ 951  459]]

 [[1007  326]
  [1012  460]]

 [[1044  337]
  [1051  455]]]


In [17]:
# linePoints = [x y x y]
def extendLineToEdges(linePoints, h, w):
    
    # y = mx + c
    
    m = (linePoints[1] - linePoints[3]) / (linePoints[0] - linePoints[2])
    
    c = linePoints[1] - m * linePoints[0]
    
    # the line can intersect any pair of edges, so we calculate them all.
    x0 = -c/m
    xH = (h-c) / m
    y0 = c
    yW = m*w + c
    
    newLinePoints = []
    
    if x0 >= 0 and x0 <= w:
        newLinePoints.append(x0)
        newLinePoints.append(0)
    if xH >= 0 and xH <= w:
        newLinePoints.append(xH)
        newLinePoints.append(h)
    if y0 >= 0 and y0 <= h:
        newLinePoints.append(0)
        newLinePoints.append(y0)
    if yW >= 0 and yW <= h:
        newLinePoints.append(w)
        newLinePoints.append(yW)
        
    return newLinePoints
    

In [18]:
image = Image.open('images/buildingUndistorted.jpg')
draw = ImageDraw.Draw(image)

h = image.height
w = image.width



for rowIndex in range(horizontalLines.shape[0]):
    line = [horizontalLines[rowIndex, 0, 0], horizontalLines[rowIndex, 0, 1], 
            horizontalLines[rowIndex, 1, 0], horizontalLines[rowIndex, 1, 1]]
    draw.line(extendLineToEdges(line, h, w), fill='#00ff00', width = 3)
    
for rowIndex in range(verticalLines.shape[0]):
    line = [verticalLines[rowIndex, 0, 0], verticalLines[rowIndex, 0, 1], 
            verticalLines[rowIndex, 1, 0], verticalLines[rowIndex, 1, 1]]
    draw.line(extendLineToEdges(line, h, w), fill='#ff2211', width = 3)

image.save('images/buildingUndistortedWithLines.jpg')

C:\Users\adhoc\Anaconda3\envs\opencv3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
C:\Users\adhoc\Anaconda3\envs\opencv3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in double_scalars
  if sys.path[0] == '':


In [19]:
image.height

804